import {
  algebraicBalance,
  arithmeticAdditionStory,
  arithmeticArrayRows,
  arithmeticDivisionShare,
  arithmeticMissingFactor,
  arithmeticMultiplicationGroups,
  arithmeticMultiStepTotal,
  arithmeticRemainderLeftover,
  arithmeticSubtractionStory,
  businessProfit,
  costBatches,
  costIngredientCombo,
  costRevenue,
  fractionHalf,
  fractionThird,
  fractionQuarter,
  optimizationBestDeal,
  ratioScale,
  visualCountAll,
  visualCountDifference,
} from "./templates.js?v=20260511-194700";

const ALL_STAGES = ["prep", "mixing", "timing", "finishing", "serving"];

export const QUESTION_BANK = [
  {
    id: "visual-count-all",
    type: "arithmetic_visual",
    subtype: "count_all",
    stages: ALL_STAGES,
    difficulty: 45,
    steps: 1,
    generator: visualCountAll,
  },
  {
    id: "visual-count-difference",
    type: "arithmetic_visual",
    subtype: "compare_groups",
    stages: ALL_STAGES,
    difficulty: 80,
    steps: 1,
    generator: visualCountDifference,
  },
  {
    id: "addition-story",
    type: "arithmetic",
    subtype: "addition_story",
    stages: ALL_STAGES,
    difficulty: 150,
    maxSR: 239,
    steps: 1,
    generator: arithmeticAdditionStory,
  },
  {
    id: "subtraction-story",
    type: "arithmetic",
    subtype: "subtraction_story",
    stages: ALL_STAGES,
    difficulty: 240,
    maxSR: 319,
    steps: 1,
    generator: arithmeticSubtractionStory,
  },
  {
    id: "multiplication-groups",
    type: "arithmetic",
    subtype: "equal_groups",
    stages: ALL_STAGES,
    difficulty: 330,
    minSR: 280,
    steps: 1,
    generator: arithmeticMultiplicationGroups,
  },
  {
    id: "array-rows",
    type: "arithmetic",
    subtype: "array_rows",
    stages: ["prep", "timing", "finishing", "serving"],
    difficulty: 390,
    minSR: 320,
    steps: 1,
    generator: arithmeticArrayRows,
  },
  {
    id: "division-share",
    type: "arithmetic",
    subtype: "share_equal_groups",
    stages: ["prep", "mixing", "timing", "finishing", "serving"],
    difficulty: 400,
    minSR: 320,
    steps: 1,
    generator: arithmeticDivisionShare,
  },
  {
    id: "missing-factor",
    type: "arithmetic",
    subtype: "missing_factor",
    stages: ["prep", "timing", "serving"],
    difficulty: 410,
    minSR: 340,
    steps: 1,
    generator: arithmeticMissingFactor,
  },
  {
    id: "cost-revenue",
    type: "cost",
    subtype: "revenue_total",
    stages: ["serving"],
    difficulty: 370,
    minSR: 300,
    steps: 1,
    generator: costRevenue,
  },
  {
    id: "cost-batches",
    type: "cost",
    subtype: "ingredient_total",
    stages: ["prep", "mixing"],
    difficulty: 360,
    minSR: 300,
    steps: 1,
    generator: costBatches,
  },
  {
    id: "cost-ingredient-combo",
    type: "cost",
    subtype: "ingredient_combo",
    stages: ["prep", "mixing"],
    difficulty: 440,
    minSR: 400,
    steps: 2,
    generator: costIngredientCombo,
  },
  {
    id: "multi-step-total",
    type: "arithmetic",
    subtype: "multi_step_total",
    stages: ["timing", "finishing", "serving"],
    difficulty: 440,
    minSR: 400,
    steps: 2,
    generator: arithmeticMultiStepTotal,
  },
  {
    id: "business-profit",
    type: "business",
    subtype: "profit",
    stages: ["serving"],
    difficulty: 460,
    minSR: 400,
    steps: 2,
    generator: businessProfit,
  },
  {
    id: "fraction-half",
    type: "fraction",
    subtype: "half_of_set",
    stages: ["mixing", "finishing", "serving"],
    difficulty: 340,
    minSR: 300,
    steps: 1,
    generator: fractionHalf,
  },
  {
    id: "fraction-third",
    type: "fraction",
    subtype: "third_of_set",
    stages: ["mixing", "finishing", "serving"],
    difficulty: 390,
    minSR: 320,
    steps: 1,
    generator: fractionThird,
  },
  {
    id: "fraction-quarter",
    type: "fraction",
    subtype: "quarter_of_set",
    stages: ["finishing", "serving"],
    difficulty: 450,
    minSR: 400,
    steps: 1,
    generator: fractionQuarter,
  },
  {
    id: "remainder-leftover",
    type: "arithmetic",
    subtype: "remainder_leftover",
    stages: ["serving"],
    difficulty: 470,
    minSR: 420,
    steps: 1,
    generator: arithmeticRemainderLeftover,
  },
  {
    id: "ratio-scale",
    type: "ratio",
    subtype: "scale_ratio",
    stages: ["mixing", "timing"],
    difficulty: 720,
    steps: 2,
    generator: ratioScale,
  },
  {
    id: "algebraic-balance",
    type: "algebraic",
    subtype: "one_variable",
    stages: ["prep", "timing"],
    difficulty: 830,
    steps: 2,
    generator: algebraicBalance,
  },
  {
    id: "optimization-best-deal",
    type: "optimization",
    subtype: "unit_rate",
    stages: ["serving"],
    difficulty: 940,
    steps: 3,
    generator: optimizationBestDeal,
  },
];
