import {
  algebraicBalance,
  arithmeticAdditionStory,
  arithmeticMultiplicationGroups,
  arithmeticSubtractionStory,
  businessProfit,
  costBatches,
  costRevenue,
  fractionHalf,
  fractionQuarter,
  optimizationBestDeal,
  ratioScale,
  visualCountAll,
  visualCountDifference,
} from "./templates.js?v=20260509-235200";

const ALL_STAGES = ["prep", "mixing", "timing", "finishing", "serving"];

export const QUESTION_BANK = [
  {
    id: "visual-count-all",
    type: "arithmetic_visual",
    subtype: "count_all",
    stages: ALL_STAGES,
    difficulty: 45,
    steps: 1,
    generator: visualCountAll,
  },
  {
    id: "visual-count-difference",
    type: "arithmetic_visual",
    subtype: "compare_groups",
    stages: ALL_STAGES,
    difficulty: 80,
    steps: 1,
    generator: visualCountDifference,
  },
  {
    id: "addition-story",
    type: "arithmetic",
    subtype: "addition_story",
    stages: ALL_STAGES,
    difficulty: 150,
    steps: 1,
    generator: arithmeticAdditionStory,
  },
  {
    id: "subtraction-story",
    type: "arithmetic",
    subtype: "subtraction_story",
    stages: ALL_STAGES,
    difficulty: 240,
    steps: 1,
    generator: arithmeticSubtractionStory,
  },
  {
    id: "multiplication-groups",
    type: "arithmetic",
    subtype: "equal_groups",
    stages: ["mixing", "timing", "serving"],
    difficulty: 540,
    steps: 1,
    generator: arithmeticMultiplicationGroups,
  },
  {
    id: "cost-revenue",
    type: "cost",
    subtype: "revenue_total",
    stages: ["prep", "timing", "serving"],
    difficulty: 220,
    steps: 1,
    generator: costRevenue,
  },
  {
    id: "cost-batches",
    type: "cost",
    subtype: "ingredient_total",
    stages: ["prep", "mixing", "serving"],
    difficulty: 320,
    steps: 1,
    generator: costBatches,
  },
  {
    id: "business-profit",
    type: "business",
    subtype: "profit",
    stages: ["finishing", "serving"],
    difficulty: 420,
    steps: 1,
    generator: businessProfit,
  },
  {
    id: "fraction-half",
    type: "fraction",
    subtype: "half_of_set",
    stages: ["mixing", "finishing"],
    difficulty: 360,
    steps: 1,
    generator: fractionHalf,
  },
  {
    id: "fraction-quarter",
    type: "fraction",
    subtype: "quarter_of_set",
    stages: ["finishing", "serving"],
    difficulty: 520,
    steps: 1,
    generator: fractionQuarter,
  },
  {
    id: "ratio-scale",
    type: "ratio",
    subtype: "scale_ratio",
    stages: ["mixing", "timing"],
    difficulty: 720,
    steps: 2,
    generator: ratioScale,
  },
  {
    id: "algebraic-balance",
    type: "algebraic",
    subtype: "one_variable",
    stages: ["prep", "timing"],
    difficulty: 830,
    steps: 2,
    generator: algebraicBalance,
  },
  {
    id: "optimization-best-deal",
    type: "optimization",
    subtype: "unit_rate",
    stages: ["serving"],
    difficulty: 940,
    steps: 3,
    generator: optimizationBestDeal,
  },
];
